- examples/advanced/advanced.go
- examples/advanced/file_unix.go
- examples/advanced/file_windows.go
- pkg/content/file.go
- pkg/content/memory.go
- pkg/content/oci.go
- pkg/content/readerat.go
- pkg/content/registry.go
- pkg/oras/copy.go
- pkg/oras/opts.go
- pkg/oras/provider.go
- pkg/target/target.go
As discussed [here](https://github.com/oras-project/oras-go/pull/8#discussion_r704212664)
> restore missing copyright headers

- examples/advanced/advanced.go
This fixes 2 issues with the example, the `--manifest-config` was implicitly mandatory and passing an empty `ocispec.Descriptor` for the `configDesc` would result in a 405 error.
> fix advanced example

- examples/advanced/advanced.go
- pkg/oras/copy.go
- pkg/oras/opts.go
Fixes #22 
cc @luisdavim 
I suspect this may need to be rebased after #25 is in, which should go first.
> add options to save layers and root manifest; remove unused opts

- content/graph.go
- content/resolver.go
- content/storage.go
- target.go
> Define `Target` interface

- README.md
See https://github.com/oras-project/oras-go/releases/tag/v1.0.0 💪 🎉 🍾 !!
Will add semver policy to the oras-project/community repo
We can then link to that from here if desired
Signed-off-by: Scott Rigby <scott@r6by.com>
> Remove construction signs

- go.mod
- go.sum
- target.go
> Update `go.mod` to `oras.land/oras-go/v2`

- registry/remote/auth/client.go
Corrected an issue where token returned from registry was not being managed properly
> Fixed registry client token

- pkg/content/errors.go
- pkg/registry/reference.go
- pkg/registry/remote/auth/cache.go
- pkg/registry/remote/auth/cache_test.go
- pkg/registry/remote/auth/challenge.go
- pkg/registry/remote/auth/challenge_test.go
- pkg/registry/remote/auth/client.go
- pkg/registry/remote/auth/client_test.go
- pkg/registry/remote/auth/credential.go
- pkg/registry/remote/auth/scope.go
- pkg/registry/remote/auth/scope_test.go
- pkg/registry/remote/internal/errutil/errors.go
- pkg/registry/remote/internal/errutil/errors_test.go
- pkg/registry/remote/internal/syncutil/once.go
- pkg/registry/remote/internal/syncutil/once_test.go
- pkg/registry/remote/repository.go
- pkg/registry/remote/url.go
- pkg/registry/remote/utils.go
- pkg/registry/remote/utils_test.go
- pkg/registry/repository.go
Backport of v2 registry tag listing to support Helm as outlined in [HIP-6](https://github.com/helm/community/blob/main/hips/hip-0006.md)
Also includes changes proposed in #88 
CC: @scottrigby @deitch @jdolitsky @scottrigby @SteveLasker
> WIP: Backport of tag listing to v1

- pkg/content/file.go
> Fix error handling on closing file store

- internal/graph/graph.go
> Fix error handling on `graph.Dispatch`

- registry/remote/repository.go
> Revise scope hints for push

- internal/ioutil/io.go
- internal/ioutil/io_test.go
- registry/remote/auth/client.go
- registry/remote/repository.go
> Fix pushing to private registries

- internal/graph/memory.go
> fix memory graph

- content/file/errors.go
- content/file/file.go
- content/file/file_test.go
- content/file/utils.go
- content/limitedstorage.go
- errdef/errors.go
> File Target

- README.md
> Update godoc badge

- registry/remote/repository.go
- registry/remote/repository_test.go
#129 Added an if check before setting a range header limit value. Added one test that performs range header check when a range header is present.
> added basic range header handling

- internal/docker/mediatype.go
Addressed https://github.com/Azure/acr-cli/pull/114#discussion_r879238877
> Const media types

- pkg/content/oci.go
Signed-off-by: viovanov <vlad@aserto.com>
> Implement Delete in the oci store content implementation

- content/file/utils.go
- content/file/utils_test.go
Fix #170 
Signed-off-by: Shiwei Zhang <shizh@microsoft.com>
> Refactor and add unit tests to File Target

- README.md
Resolves #180 
Signed-off-by: Lixia (Sylvia) Lei <lixia_lei@outlook.com>
> Add example links in README

- pkg/content/oci.go
Signed-off-by: oanatmaria oana@aserto.com
> Implement Info in the oci store content implementation

- copy.go
- copy_test.go
- extendedcopy.go
Resolves #189
Signed-off-by: Lixia (Sylvia) Lei <lixia_lei@outlook.com>
> Support FindSuccessors option

- MIGRATION_GUIDE.md
- README.md
> Add migration guide

- README.md
Resolves #215 
Signed-off-by: Lixia (Sylvia) Lei <lixia_lei@outlook.com>
> Add auth examples in README

- registry/registry.go
- registry/remote/example_test.go
- registry/remote/registry.go
- registry/remote/registry_test.go
- registry/remote/repository.go
- registry/remote/repository_test.go
- registry/remote/utils.go
- registry/repository.go
> Support last parameter for listing catalog and tags

- content/file/file_test.go
- content/graph.go
- content/memory/memory_test.go
- content/oci/oci_test.go
- extendedcopy_test.go
- go.mod
- go.sum
- registry/remote/example_test.go
Update artifact-spec version and adjust code accordingly.
Resovles #221 
Signed-off-by: Lixia (Sylvia) Lei <lixia_lei@outlook.com>
> Update artifact spec to v1.0.0-rc.1

- registry/remote/repository.go
- registry/remote/repository_test.go
> Skip version checking for pre-RC1 endpoint

- registry/remote/example_test.go
> added one example for downloading artifact reference manifest

- registry/remote/example_test.go
Part of issue #178 
Added an example of pulling the blobs of an ORAS artifact manifest.
> created pull blob example

- example_test.go
> added an example of copying artifact manifest

- go.mod
- go.sum
> update artifact-spec to v1.0.0-rc.2

- registry/remote/auth/client.go
- registry/remote/repository.go
Resolves #252 
Signed-off-by: Billy Zha <jinzha1@microsoft.com>
> Reuse post token for put when pushing blobs

- registry/remote/example_test.go
Following pr #245 
Following issue #128
> replaced io.ReadAll with content.ReadAll in examples

- example_test.go
> Added an example of using ExtendedCopy

- pack.go
- pack_test.go
> Upload empty blob when packing

- example_test.go
fix typo in example test
Signed-off-by: Zoey Li <zoeyli@microsoft.com>
> fix: fix typo in example test

- registry/reference.go
- registry/reference_test.go
This is the nice-to-have changes that was split out of #225.
Signed-off-by: Nima Talebi <nima@users.noreply.github.com>
> refactor: Small refactor of reference module and tests

- content_test.go
- copy_test.go
- internal/platform/platform.go
- internal/platform/platform_test.go
improve err msg
Resolves: https://github.com/oras-project/oras-go/issues/290
Signed-off-by: Zoey Li <zoeyli@microsoft.com>
> refactor: improve error message on platform mismatch in order to distinguish platform not found and manifest not found

- registry/remote/repository.go
Fixes https://github.com/oras-project/oras/issues/594
> fix: fix 404 error message for `manifestStore.FetchReference`

- go.mod
- go.sum
Signed-off-by: Sajay Antony <sajaya@microsoft.com>
> Update image-spec to v1.1.0-rc2

- registry/repository.go
> feat!: add `ReferrerFinder` to `Repository` interface

- copy.go
- copy_test.go
> feat: skip foreign layers on `oras.Copy`

- copy.go
- copy_test.go
Resolves #383 
Signed-off-by: Billy Zha <jinzha1@microsoft.com>
> fix: use proxy when copying node with successors

- .github/workflows/build-pr.yml
- .github/workflows/build.yml
- go.mod
> build: update to Go 1.18

- content.go
- content_test.go
- registry/remote/example_test.go
> fix!: `Tag()` and `TagN()` return a descriptor

- copy.go
- extendedcopy.go
> refactor: optimize performance for Extended Copy

- content/file/example_test.go
- content/file/file.go
- content/file/file_test.go
Resolves: #345
BREAKING CHANGE: Remove `file.PackFiles()`
> remove!: Remove `file.PackFiles()` and add an example instead

- .github/dependabot.yml
- Target `v1` branch for golang updates until `v2` is GA
- Add check for GitHub Actions
> build: add dependabot for `v1` branch, add GitHub Actions

- content/file/file_unix_test.go
- content/oci/storage.go
> test: improve the symlink unit tests for file store

- README.md
- content.go
- content/file/file.go
- content/oci/oci.go
- content/oci/readonlyoci.go
- content/oci/storage.go
- copy.go
- extendedcopy.go
- pack.go
- registry/remote/auth/client.go
- registry/remote/auth/scope.go
- registry/remote/registry.go
- registry/remote/repository.go
- registry/repository.go
> doc: Update README and clean up godoc comments

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- go.mod
Update Go support window to [1.19, 1.20]
Fixes: #425 
Cc: @shizhMSFT
> feat: update go support window to [1.19, 1.20]

- go.mod
- go.sum
- pkg/auth/docker/login_tls.go
since there is a small api change, one has to do the update manually
> bump: update docker and docker/cli

- content/oci/oci.go
- content/oci/oci_test.go
- content/oci/readonlyoci.go
> fix: ensure `index.json` for oci store

- go.mod
- go.sum
- internal/spec/artifact.go
- pack.go
- pack_test.go
> refactor: upgrade go mod to `image-spec v1.1.0-rc4` and fix the missing types

- content/oci/storage.go
- content/oci/storage_test.go
Signed-off-by: Xiaoxuan Wang <wangxiaoxuan119@gmail.com>
Part 3/4 of #454
Based on draft PR #582
> feat: support deletion for OCI storage

- registry/example_reference_test.go
- registry/reference.go
Resolves #671 
Related to #670
> docs: add example to parse reference with digest

- go.mod
- go.sum
> build(deps): bump github.com/opencontainers/image-spec from 1.1.0-rc5 to 1.1.0-rc6

- .github/workflows/build-pr.yml
- .github/workflows/build.yml
- go.mod
> build: update to Go 1.19

- .github/workflows/build-pr.yml
- .github/workflows/build.yml
- go.mod
> build: update to Go 1.20

- copy_test.go
- go.mod
- go.sum
- internal/syncutil/limit.go
> fix: cancel goroutine before the next one is created

- .github/.codecov.yml
> build: enforce diff code coverage of 80%

- .github/workflows/build-pr.yml
- .github/workflows/build.yml
- go.mod
> build(go): upgrade go version to v1.22

- go.mod
- go.sum
> build(deps): bump github.com/distribution/distribution/v3 from 3.0.0-alpha.1 to 3.0.0-beta.1

- registry/remote/retry/policy.go
> refactor: fix seed for retry policy

- .github/workflows/stale.yml
> chore(workflow): add stale bot

- registry/remote/repository.go
> docs: update doc for ReferrerListPageSize

- content/file/utils_test.go
> test: fix test cases in content/file/utils_test.go

- .github/workflows/build-pr.yml
- .github/workflows/build.yml
- go.mod
> build(go): upgrade go version to v1.23 for v1

- go.mod
- go.sum
> build(deps): bump github.com/distribution/distribution/v3 from 3.0.0-rc.3 to 3.0.0-rc.4

- example_copy_test.go
- example_test.go
- registry/remote/example_test.go
> docs: add more practical examples

- pack_test.go
Add some test cases for `validateMediaType` in `pack_test.go`.
> test: add unit tests for validateMediaType

- docs/tutorial/quickstart.md
- tutorial/quickstart.md
> docs: add quick start for oras-go

- registry/registry.go
- registry/remote/auth/challenge.go
- registry/remote/auth/client.go
- registry/remote/auth/credential.go
- registry/remote/auth/example_test.go
- registry/remote/auth/scope.go
- registry/remote/errcode/errors.go
- registry/remote/registry.go
- registry/remote/repository.go
- registry/remote/url.go
- registry/repository.go
> docs: updated broken links
