README.md, examples/simple_push_pull.go, go.mod, pkg/auth/docker/client.go, pkg/auth/docker/client_test.go, pkg/auth/docker/login.go, pkg/auth/docker/logout.go, pkg/auth/docker/resolver.go, pkg/content/decompressstore_test.go, pkg/content/file_test.go, pkg/content/multireader_test.go, pkg/content/passthrough_test.go, pkg/oras/oras_test.go, pkg/oras/pull.go, pkg/oras/pull_opts.go, pkg/oras/push.go, pkg/oras/push_opts.go, pkg/oras/store.go
Just for fun. I've enabled it on the website:
```
$ curl https://oras.land/oras-go
<!doctype html><html lang=en-us><head><meta charset=utf-8><meta name=go-import content="oras.land/oras-go git https://github.com/oras-project/oras-go"><meta name=go-source content="oras.land/oras-go git https://github.com/oras-project/oras-go https://github.com/oras-project/oras-go/tree/main{/dir} https://github.com/oras-project/oras-go/blob/main{/dir}/{file}#L{line}"><meta http-equiv=refresh content="0; url=https://github.com/oras-project/oras-go"></head><body>Nothing to see here; <a href=https://github.com/oras-project/oras-go>move along</a>.</body></html>
```
Let me know if any objection
=> Use oras.land vanity import

examples/advanced/advanced.go, examples/simple/simple_push_pull.go, pkg/content/content_test.go, pkg/content/file.go, pkg/content/manifest.go, pkg/content/memory.go, pkg/oras/oras_test.go
Also updates the advanced example to support annotations. This is a potential fix for #22 , and also supersedes #24 
cc @luisdavim
=> add support for manifest and config annotations at generation time

pkg/go.mod, pkg/go.sum
Remediation for the vulnerabilities
-  https://github.com/opencontainers/distribution-spec/security/advisories/GHSA-mc8v-mgrf-8f4m
-  https://github.com/opencontainers/image-spec/security/advisories/GHSA-77vh-xpmg-72qh
Signed-off-by: Tejaswini Duggaraju <naduggar@microsoft.com>
=> Upgraded containerd and OCI spec versions

examples/go.mod, examples/go.sum
This should fix the acceptance tests issue https://github.com/oras-project/oras-go/runs/4256641445?check_suite_focus=true 
Signed-off-by: Tejaswini Duggaraju <naduggar@microsoft.com>
=> Fixed examples to use the new versions of containerd and OCI image spec

go.mod, go.sum
Remediation for the vulnerabilities 
-  https://github.com/opencontainers/distribution-spec/security/advisories/GHSA-mc8v-mgrf-8f4m
-  https://github.com/opencontainers/image-spec/security/advisories/GHSA-77vh-xpmg-72qh
Signed-off-by: Tejaswini Duggaraju <naduggar@microsoft.com>
=> Updated the versions of containerd and OCI spec

go.mod, go.sum, pkg/content/registry.go, pkg/target/docker/discoverer.go
- Use the same resolver options that were used to create a resolver when creating discoverer. 
- Currently only two modes of auth are supported. One is credentials through username/password and other is through docker config. 
- This is a stop gap solution till oras is refactored to provide an Auth interface that lets different implementations like k8s chain to use for registry auth
=> [Artifacts]Fix registry auth with Discoverer

content/storage.go, errdef/errors.go, registry/reference.go, registry/reference_test.go, registry/registry.go, registry/repository.go
=> Registry Interface

content/memory/memory.go, content/memory/memory_test.go, copy_test.go, internal/descriptor/descriptor.go, internal/resolver/memory.go, internal/resolver/memory_test.go
- Resolves #54.
- Add test for `oras.Copy()` using the `Memory` target.
=> Memory Target

go.mod, internal/httputil/seek.go, internal/syncutil/once.go, internal/syncutil/once_test.go, registry/remote/auth/cache.go, registry/remote/auth/cache_test.go, registry/remote/auth/challenge.go, registry/remote/auth/challenge_test.go, registry/remote/auth/client.go, registry/remote/auth/client_test.go, registry/remote/auth/credential.go, registry/remote/auth/scope.go, registry/remote/auth/scope_test.go, registry/remote/internal/errutil/errors.go, registry/remote/internal/errutil/errors_test.go, registry/remote/registry.go, registry/remote/registry_test.go, registry/remote/repository.go, registry/remote/repository_test.go, registry/remote/url.go, registry/remote/utils.go, registry/remote/utils_test.go
Registry authentication implementation for #57.
Change logs:
- Implementation authentication for the registry client.
- Resolves #57.
- Addresses comments in #82.
- Bump up golang version from `v1.16` to `v1.17` due to the use of new built-in library functions.
=> Registry Auth Client

registry/remote/utils.go
Auth scope currently makes use of a repository reference, but should make use of the repository field instead.
=> Corrected auth scope repository

pkg/auth/docker/client.go
related to https://github.com/helm/helm/pull/10536
cc @scottrigby
=> Enable fallback on Docker config using custom auth file

.github/workflows/build-pr.yml, .github/workflows/build.yml, Makefile, scripts/acceptance.sh, scripts/test.sh
Resolves #61.
- Update and clean up Makefile.
- Fix test script.
- Detect examples instead of hard coding.
- Update go version to `1.17.6` for testing.
=> Update Makefile and scripts

content/oci/oci.go, content/oci/oci_test.go, content/oci/storage_test.go
Fixes #123 
Also replaced `os.MkdirTemp` with `t.TempDir()`
=> Ensure OCI root directory

registry/remote/repository.go, registry/remote/repository_test.go, registry/repository.go
=> Add FetchReference() for Repository Target

pkg/oras/provider.go
fixes https://github.com/oras-project/oras-go/issues/141
=> use io.ReadFull for ProviderWrapper in case of partial read

registry/remote/repository.go, registry/remote/repository_test.go, registry/remote/url.go, registry/remote/url_test.go
Resolves #140 
Tested against oras-distribution and ACR DF3
=> Filter referrers by artifact type

registry/remote/auth/example_test.go
Completes and resolves #60 
Resolves #149 
---
Examples of using the http client.
=> examples for the auth module

registry/remote/auth/example_test.go
Following pr #182 
A patch for issue #149 
Moved clientConfigExample to the front, and added refreshTokenExample at the end.
=> added a refresh token example

registry/remote/repository.go, registry/remote/repository_test.go
=> Check ORAS-Api-Version for referrers API

pack.go, pack_test.go
Add `PackArtifact` to support packing ORAS Artifact Manifest, and set a default `io.cncf.oras.artifact.created` annotation.
Resolves #175
Resolves #202
Related: #205, #206
=> Add PackArtifact

copy.go, copy_test.go
=> Bug: oras.Copy() may skip tagging if manifest blob already exists in the destination

content/file/file.go, content/file/file_test.go, copy_test.go
=> Failed to download all the files in an artifact using oras.Copy()

content/file/errors.go, content/file/file.go, content/file/file_test.go
=> Allow skipping unnamed blobs when pushing to file store

extendedcopy.go, extendedcopy_test.go
=> support filtering on annotation with regex

content.go, content_test.go, copy.go, copy_test.go, internal/docker/mediatype.go, internal/platform/platform.go, internal/platform/platform_test.go
Support platform selection on Copy by adding `AddPlatformFilter` func that configure the `MapRoot` option for clients.
Platform property ref: [OCI Image Index Specification](https://github.com/opencontainers/image-spec/blob/main/image-index.md#oci-image-index-specification)
The given platform matches the target platform if all of the below conditions are met:
- Architecture and OS exactly match.
- Variant and OSVersion exactly match if target platform provided.
- OSFeatures of the target platform are the subsets of the OSFeatures array of the given platform.
- Features property is reserved for future versions of the specification, will skip this for now. ref: [descriptor.go](https://github.com/opencontainers/image-spec/blob/main/specs-go/v1/descriptor.go#L50)
Note: Variant, OSVersion, …
=> feat: Support platform selection on Copy

extendedcopy.go, extendedcopy_test.go, registry/repository.go
=> added filtering by artifact type with regex

extendedcopy.go, extendedcopy_test.go
Fix the bug that filtering does not work when no annotations exists in the descriptor. In this case, we fetch and parse the manifest to get the annotations.
Resolves #265 
=> fix: added manifest parsing when annotation is not in the descriptor

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml, go.mod
Update support window to Go 1.18, 1.19.
Resolves #261 
=> build: update support window to Go 1.18, 1.19

go.mod, go.sum
Bump docker/distribution to address [CWE-843](https://cwe.mitre.org/data/definitions/843.html)
=> bump docker/distribution to v2.8.1

registry/remote/repository.go, registry/remote/repository_test.go
See https://github.com/oras-project/oras-go/issues/225 for details, but here's the **tldr**:
```
% oras pull 080565210187.dkr.ecr.us-west-2.amazonaws.com/my.repo:my.tag
Error: GET "https://080565210187.dkr.ecr.us-west-2.amazonaws.com/v2/my.repo/manifests/my.tag": empty response Docker-Content-Digest
```
The expected outcome (what this PR claims to fix):
```
% oras pull 080565210187.dkr.ecr.us-west-2.amazonaws.com/my.repo:my.tag
Downloading 3cd22ae067a3
Downloaded empty artifact
Pulled 080565210187.dkr.ecr.us-west-2.amazonaws.com/my.repo:my.tag
Digest: sha256:32aef68c20b6f25d69ecbc2f3f98e28f6f6fdacade75ee879459b61f610583f0
```
Resolves #225
=> fix: oras pull error `empty response Docker-Content-Digest`

pack.go
=> fix: remove `+json` encoding from the default config media type

pack.go
Reverts oras-project/oras-go#288
Related to #294 
=> fix: Revert "fix: remove `+json` encoding from the default config media type"

copy.go
=> fix: use a default value when `Concurrency` is not specified

content.go, content_test.go, copy.go, copy_test.go, internal/cas/proxy.go, internal/cas/proxy_test.go
Resolves #291 
Fixes #298
BREAKING CHANGE: Rename `oras.TagBytesOptions` to `oras.TagBytesNOptions`
=> feat!: Support specifying `MaxMetadataBytes` option for `oras.Resolve` and `oras.Copy`

content/resolver.go, registry/remote/repository.go, registry/remote/repository_test.go, registry/repository.go
=> feat: `Repository.Manifest()` now returns a `ManifestStore`

registry/remote/repository.go
Performance optimization based on #287
=> feat: implement ReferenceParser for manifestStore

registry/remote/interface_test.go, registry/remote/interface_test/interface_test.go, registry/remote/repository_test.go
Add interface tests for `remote.Repository`, `remote.blobStore` and `remote.manifestStore`
Resolves #302 
=> test: add interface tests for Repository, blobStore and manifestStore

.github/.codecov.yml, .github/dependabot.yml, .github/workflows/build.yml, .github/workflows/codeql-analysis.yml, registry/remote/url_test.go
This PR will fix the missing license headers mentioned in #314 using the [skywalking-eyes](https://github.com/apache/skywalking-eyes) fix header tool.
Header check result is shown as follows:
```
INFO Loading configuration from file: .licenserc.yaml 
INFO Totally checked 410 files, valid: 86, invalid: 5, ignored: 319, fixed: 0 
INFO GITHUB_TOKEN is not set, license-eye won't comment on the pull request 
ERROR the following files don't have a valid license header: 
.github/.codecov.yml
.github/dependabot.yml
.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
registry/remote/url_test.go
ERROR one or more files does not have a valid license header
```
Signed-off-by: JasmineTang <jasminetang@microsoft.com>
=> fix: add missing license headers

copy_test.go, internal/platform/platform.go, internal/platform/platform_test.go
Resolves: https://github.com/oras-project/oras/issues/600
Signed-off-by: Zoey Li <zoeyli@microsoft.com>
=> fix: improve oras manifest fetch --platform error message

content/file/file_test.go, content/graph.go, content/memory/memory_test.go, content/oci/oci_test.go, example_test.go, extendedcopy.go, extendedcopy_test.go, go.mod, go.sum, internal/descriptor/descriptor.go, registry/remote/example_test.go, registry/remote/manifest.go, registry/remote/repository.go, registry/remote/repository_test.go, registry/repository.go
The work of migrating ORAS Artifact to OCI Artifact is partially done on the `oci-playground/oras-go` main branch.
We will continue the migration work on `oras-project/oras-go` main branch going forward.
Resolves #307 
Resolves #308 
BREAKING CHANGE: change the parameter type of `Referrers`
=> feat!: support OCI artifact manifest with descriptor migration

registry/reference.go, registry/reference_test.go, registry/remote/repository.go, registry/remote/repository_test.go
This change prevents a token sneaking in as a *tag*, then later getting validated as a *digest*.  In order to do that, a new struct member has been introduced to `registry.Reference`, namely, `ReferenceType`.  This can take one of the small finite set of values: `Undefined`, `None`, `Tag`, and `Digest`.  `None` is applicable only to *valid form D*, and `Undefined` is the `zero/null/empty` default value to force explicitness.
~~Also note that in *valid form B*, we're still allowing the redundant `tag`, is there a reason to allow for this (as opposed to considering it ambiguous, and deeming it invalid)?~~ just noticed this was already answered by @Wwwsylvia in #303.
Resolves #303.
Signed-off-by: Nima Talebi <github@nima.id.au>
=> fix: Scrutinize references for digests posing as tags

content/graph.go, extendedcopy.go, extendedcopy_test.go
According to [Open Container Initiative Distribution Specification](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#listing-referrers), the `Referrers API` must include the artifact type and annotations of the referrers in the returned descriptor list. 
> The descriptors MUST include an artifactType field that is set to the value of artifactType for an artifact manifest if present, or the configuration descriptor's mediaType for an image manifest. The descriptors MUST include annotations from the image or artifact manifest.
However, the `Predecessors` function implemented by file, OCI, and memory store is not guaranteed to include the artifact type and annotations in the returned descriptors.
This PR is migrated from https://github.com/oci-playground/oras-go/pull/3. …
=> refactor: optimize extended copy filters

registry/remote/example_test.go, registry/remote/repository.go, registry/remote/repository_test.go, registry/remote/utils.go
=> feat: index referrers on manifest push

registry/remote/repository.go, registry/remote/repository_test.go
=> feat: index referrers on manifest delete

registry/remote/errcode/errors.go, registry/remote/internal/errutil/errutil.go, registry/remote/internal/errutil/errutil_test.go, registry/remote/repository.go, registry/remote/repository_test.go
1. Use zero digest (`sha256:0000000000000000000000000000000000000000000000000000000000000000`) for pinging referrers API
2. Check `NAME_UNKNOWN` error code
Related to #271
Related to #354 
Related to https://github.com/opencontainers/distribution-spec/issues/359
=> refactor: refactor functions related to querying referrers

registry/reference.go
=> doc: revise doc of `registry.Reference`

registry/remote/example_test.go
Fix the function name of a testable example so that the example can be showed on godoc.
Related to #304
=> doc: fix testable example name

internal/slices/slice.go, registry/remote/registry.go, registry/remote/registry_test.go, registry/remote/repository.go
The `Repository` struct contains mutex state (in the `sync.Mutex` and `syncutil.Pool`). When converting `RepositoryOptions` values to `Repository` values, this mutex state is copied. This change prevents the internal state from being copied by passing `RepositoryOptions` around by reference and explicitly copying the visible fields.
=> fix: avoid copying Repository mutex state

registry/remote/example_test.go, registry/remote/repository.go, registry/remote/repository_test.go
=> fix: attempt range query only if server explicitly supports

copy.go, extendedcopy.go, pack.go
**Typed** constants/variables are displayed next to the declaration of their type.
Resolves #304
=> doc: make the default options displayed next to the option type on godoc

registry/remote/repository.go
The `oras` client and Go SDK may fail when a registry using HTTP/1.1 responds with a chunked response body, as the `content-length` header will be absent (`resp.ContentLength == -1`).
This adds support for registry servers such as `zot` which respond with `transfer-encoding: chunked` responses. 
I have not added tests, being unfamiliar with the testing harness in this library. Contributions to this branch are welcome from maintainers to address that.
Fixes #374
Before:
```shell
docker run -p 5000:5000 ghcr.io/project-zot/zot-linux-amd64:latest
```
```shell
cd $(mktemp -d)
for f in $(seq 1 20); do echo "$f" > "artifact-${f}.txt"; done
oras push localhost:5000/foo/bar:v1.0 artifact-*.txt
oras manifest fetch localhost:5000/foo/bar:v1.0
```
After:
```shell
oras manifest fetch …
```
=> fix: allow chunked responses via HEAD request fallback

content/oci/oci.go, content/oci/oci_test.go, content/oci/readonlyoci.go, content/oci/readonlyoci_test.go, content/oci/readonlystorage.go, content/oci/readonlystorage_test.go, content/oci/storage.go, registry/reference.go, registry/remote/registry.go, registry/remote/repository.go, registry/repository.go
Will support creating OCI store from tarball in next PR.
Resolves: #336 
=> feat: support creating read-only OCI store from `fs.FS`

content.go, copy.go, internal/descriptor/descriptor.go, internal/docker/mediatype.go
Resolves #319
Current result with oras-cli:
```
$ oras copy docker.io/library/hello-world@sha256:314cc0309465c7be2936df274b258c843f5a49eb21f63b719d60b51564070b8f wxxacr.azurecr.io/temp439:test00
$ Error: the artifact with foreign layer sha256:5ead999142ecce15e02523c49706a633fa708374d94bb65a254e3a3c117d609b is not supported: sha256:5ead999142ecce15e02523c49706a633fa708374d94bb65a254e3a3c117d609b: not found
```
=> feat: change foreign layer error message at repository.Fetch()

content/descriptor.go, content/descriptor_test.go, content/oci/oci.go, content/oci/oci_test.go, content/oci/readonlyoci.go, content/oci/readonlyoci_test.go, content/oci/readonlystorage.go, internal/descriptor/descriptor.go
1. Support discovering predecessors that are not tagged
2. Support resolving a manifest by its digest
3. Support resolving a blob by its digest
Resolves: #342
=> refactor: refactor OCI store to fully support `Predecessors()` and `Resolve()`

README.md
=> doc: Remove @main from the godoc URLs in README 

content/file/example_test.go, content/file/file.go, content/file/file_test.go, content/file/file_unix_test.go, content/file/utils.go, copy_test.go
Fixes part of #404
Fixes: #402
BREAKING CHANGE: `file.New()` and other constructors now return an error
=> fix!: fix error when extracting folder containing symbolic links

content/oci/oci.go, content/oci/oci_test.go, content/oci/storage.go, content/oci/storage_test.go, internal/fs/tarfs/tarfs.go, internal/fs/tarfs/tarfs_test.go
Fixes: #404 
BREAKING CHANGE: `oci.NewStorage()` now returns an error
=> fix!: use absolute path for OCI root

example_test.go, registry/example_test.go, registry/remote/auth/client.go, registry/remote/auth/client_test.go, registry/remote/example_test.go, registry/remote/retry/client.go, registry/remote/retry/client_test.go, registry/remote/retry/policy.go, registry/remote/retry/policy_test.go
fixes #147 
If implemented, this will provide a default http client with retry.
The retry function is an exponential back off 0.25s * 2^n ± 10% and max 5 attempts.
The client is the default client of `auth.Client`
Co-authored-by: Shiwei Zhang <shizh@microsoft.com>
Signed-off-by: Soule BA <bah.soule@gmail.com>
cc @shizhMSFT
=> feat!: retryable http client

README.md
Signed-off-by: khanjasir90 <khanmohdjasir@gmail.com>
fix: #437 
Description: Updated link of oras-go in readme.md file
=> fix: broken go-sdk link in readme

.github/licenserc.yml, CODEOWNERS
Add [CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) based on the [OWNERS.md](https://github.com/oras-project/oras-go/blob/main/OWNERS.md) file.
=> chore: add CODEOWNERS based on OWNERS.md

content/oci/oci.go, content/oci/oci_test.go, content/oci/readonlyoci.go, content/oci/readonlyoci_test.go
Based on discussion on https://github.com/oras-project/oras-go/issues/457, this PR returns a full descriptor on Resolve when the method it's called by tag and it returns a plain descriptor when the method it's called by digest.
=> fix: OCI store resolve returns full descriptor

content/file/file_test.go, content/graph.go, content/memory/memory_test.go, content/oci/oci_test.go, content/oci/readonlyoci_test.go, copy_test.go, example_test.go, extendedcopy.go, extendedcopy_test.go, go.mod, go.sum, internal/descriptor/descriptor.go, internal/spec/artifact.go, pack.go, pack_test.go, registry/remote/example_test.go, registry/remote/manifest.go, registry/remote/referrers.go, registry/remote/referrers_test.go, registry/remote/repository.go, registry/remote/repository_test.go
This PR fixes and only fixes the compiling errors due to the breaking changes introduced by `image-spec v1.1.0-rc.3` where the artifact manifest related specs are removed.
Fix #495.
Fix partially #494
=> build: upgrade image-spec to v1.1.0-rc.3

registry/remote/auth/client.go, registry/remote/auth/client_test.go
=> fix: add special handling for "docker.io" in `StaticCredential()`

content/oci/oci.go, content/oci/readonlyoci_test.go, content/oci/readonlystorage.go, content/oci/readonlystorage_test.go, content/oci/storage_test.go
https://github.com/opencontainers/image-spec/blob/v1.0/image-layout.md#content specifies that the blobs dir must exist, so the changed ensureDir in this PR is a bugfix.
The addition and use of the ociBlobsDir constant is more of a cleanup suggestion, and I can remove it if necessary. I've also asked for it to be added upstream at https://github.com/opencontainers/image-spec/issues/1069 but that will probably take significantly longer.
=> fix(oci): create blobs dir and define blobs dir name constant

content/oci/oci.go, content/oci/readonlyoci.go, content/reader.go
NewWithContext refers to both the `oci-layout` and `index.json` as "OCI Image Layout", this PR fixes the latter.
ReadAll is a deeper change that will improve error reporting for a lot of cases, at the cost of error volume. Some or all of that change could happen higher up to satisfy this particular issue. I think the expected/actual size output belongs here. There seem to be more than a few code paths in this and other repos that end up calling ReadAll multiple times without reporting which call produced an error so I think it's appropriate to also output the digest here, but that's less compelling.
The Verify comment clears up confusion I encountered while working on this issue. "verifies size" implies checking for both too big AND too small, but it only checks if the file is bigger (or …
=> fix: improve errors for `ReadAll` and `loadIndexfile`

go.mod, go.sum, pkg/auth/docker/login_tls.go
Handle `registry.Service` change from interface to struct.
I've seen https://github.com/oras-project/oras-go/pull/517 and https://github.com/oras-project/oras-go/pull/519 and am not clear why they were closed.
The old docker/docker dependency is blocking updating other dependencies in the containers ecosystem, where oras-go v1 is still in use. Would be grateful if the update could be applied to v1.
=> deps: update docker/docker to v24.0.2 (v1)

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/license-checker.yml, content/oci/oci.go, content/oci/readonlyoci.go, content/oci/readonlyoci_test.go, content/oci/readonlystorage.go, content/oci/readonlystorage_test.go, content/oci/storage_test.go, content/reader.go, go.mod, go.sum, internal/spec/artifact.go, pack.go, pack_test.go
Cherry-picked the following commits from the main branch:
- [b4400e1e522dfd7736af4eae1aacb90b43686629](https://github.com/oras-project/oras-go/commit/b4400e1e522dfd7736af4eae1aacb90b43686629)
- [2e7b65f1b60d11cd861ce6b68bc53e23a1fd9306](https://github.com/oras-project/oras-go/commit/2e7b65f1b60d11cd861ce6b68bc53e23a1fd9306)
- [6b5bd4b4372b8ba8f5ec0251ddffba8f360f5cf1](https://github.com/oras-project/oras-go/commit/6b5bd4b4372b8ba8f5ec0251ddffba8f360f5cf1)
- [4763cd4ba3b7040dd72de5b06c970c9a9008607b](https://github.com/oras-project/oras-go/commit/4763cd4ba3b7040dd72de5b06c970c9a9008607b)
- [babfc511e0a0d61293e4a305f29f206d0b4ac984](https://github.com/oras-project/oras-go/commit/babfc511e0a0d61293e4a305f29f206d0b4ac984)
=> chore: patch for release-2.2

content/storage.go, pack.go, pack_test.go
1. Introduce `PackOptions.PackManifestType`
2. Introduce `DefaultPackOptions`
Resolves: #532
=> feat: add a PackOption to support packing image manifests that conform to image-spec v1.1.0-rc4

registry/remote/referrers.go, registry/remote/referrers_test.go, registry/remote/repository.go, registry/remote/repository_test.go
=> feat: update Referrers API for distribution-spec v1.1.0-rc3

registry/remote/repository.go, registry/remote/repository_test.go
1. Support pushing image index with a subject
2. Check the "OCI-Subject" header
Resolves: #534
=> feat: update the implementation of pushing manifest for distribution-spec v1.1.0-rc3

registry/remote/repository.go, registry/remote/repository_test.go
Support deleting image indexes with a subject
Resolves: #535
=> feat: update the implementation of deleting manifest for distribution-spec v1.1.0-rc3

content/oci/oci.go, content/oci/readonlyoci.go, content/oci/readonlystorage.go, content/oci/storage.go, registry/reference.go, registry/remote/errcode/errors.go, registry/remote/referrers.go, registry/remote/registry.go, registry/remote/repository.go, registry/remote/url.go, registry/repository.go
=> docs: update links

example_test.go
Following up issue #434 
Displayed with `godoc -play -http=:6061`, we get [larger examples](https://go.dev/blog/examples#:~:text=ExampleString_second()%0Afunc%20ExampleString_third()-,Larger%20examples,-Sometimes%20we%20need) with godoc.
=> docs: display larger example

pack.go, pack_test.go
Related issue: #532 
Related discussion: https://github.com/oras-project/oras/issues/1011#issuecomment-1664614098
=> fix: pack should not set `artifactType` when config is specified

example_pack_test.go, example_test.go, pack.go, pack_test.go
This PR refactors `oras.Pack` that was updated by #532.
1. Move the support of Image Manifest `v1.1.0-rc4` to `PackManifest`
2. Deprecate `Pack`
Resolves: #568
=> refactor: add `PackManifest` and deprecate `Pack`  

pack.go
I'm splitting PR #572 into 2 parts, this is the first part.
=> refactor: refactor unexported pack methods

errdef/errors.go, example_test.go, pack.go, pack_test.go
=> feat: validate input media type for `oras.PackManifest `

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml, README.md, go.mod
1. Update go mod version to `1.20`
2. Update go version matrix in workflow config files
3. Update README
Resolves: #583
=> build: bump go version

registry/remote/repository.go, registry/remote/repository_test.go
=> fix: push an empty index when deleting the last referrer with SkipReferrersGC

registry/remote/credentials/memory_store.go, registry/remote/credentials/memory_store_test.go
Features:
-  Add `MemoryStore`
I submitted a pull request for MemoryStore to `oras-credentials-go` a week ago. However, the repository has since been deprecated. I've created an identical PR to [this one](https://github.com/oras-project/oras-credentials-go/pull/92).
Reference Issue: [Here](https://github.com/oras-project/oras-credentials-go/issues/89)
=> feat: Add 'MemoryStore'

registry/remote/credentials/memory_store.go, registry/remote/credentials/memory_store_test.go
1. Un-expose `credentials.MemoryStore` as it is unecessary to be public
2. Make `credentials.NewMemoryStore` return an interface instead of a struct
=> refactor: make credentials.NewMemoryStore return an interface

registry/remote/repository.go, registry/remote/repository_test.go
=> fix: Avoid a copy of sync.Mutex in Repository

copy.go
=> fix: correctly handle OnCopySkipped

content/oci/oci.go, content/oci/oci_test.go, content/oci/readonlyoci.go, content/oci/readonlyoci_test.go, content/oci/readonlystorage.go, content/oci/readonlystorage_test.go, content/oci/storage_test.go, go.mod, go.sum, registry/remote/example_test.go
1. Bump `github.com/opencontainers/image-spec` to `v1.1.0-rc5` in go mod
2. Replace "index.json" and "blobs" with corresponding constants in the spec
3. Fix testable examples that broke by the spec change - `MediaType` became a required field in `Descriptor`
Resolve: #599
=> build: bump `github.com/opencontainers/image-spec` to `v1.1.0-rc5`

registry/remote/credentials/internal/config/config.go, registry/remote/credentials/internal/config/config_test.go, registry/remote/credentials/testdata/legacy_auths_config.json
=> fix: package `credentials` to support legacy auth keys in docker config

registry/remote/repository.go
Add `pull` and `delete` scope hints before attempting client-side indexing on manifest delete.
Resolve: #594 
Before this change, the requests produced during deleting a manifest when Referrers API is not known to be available:
- Request `#0`: GET manifest - 401
- Request `#1`: POST token (scope: pull) - 200
- Request `#2`: GET manifest - 200
- **[optional]** Request `#3`: GET referrers index - 200
- **[optional]** Request `#4`: PUT referrers index - 401
- **[optional]** Request `#5`: POST token (scope: pull, push) - 200
- **[optional]** Request `#6`: PUT referrers index - 201
- <ins> Request `#7`: DELETE manifest - 401  </ins>
- <ins> Request `#8`: POST token (scope: delete)  </ins>
- Request `#9`: DELETE manifest - 202
After this change, the requests should become:
- Request `#0`: GET …
=> perf: reduce auth request count for manifest delete

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/license-checker.yml, README.md, SECURITY.md, content/oci/oci.go, content/oci/oci_test.go, content/oci/readonlyoci.go, content/oci/readonlyoci_test.go, content/oci/readonlystorage.go, content/oci/readonlystorage_test.go, content/oci/storage_test.go, copy.go, go.mod, go.sum, registry/remote/example_test.go, registry/remote/repository.go, registry/remote/repository_test.go
Cherry-picked the following commits from the main branch onto the `release-2.3` branch:
- 0582b77a64aee62610e26ad3a79937d9060dd910: #579 
- 92eb05c677fc9aea34b5bbca7199ecc7b497e6bd: #585 
- 4a52cfdc8e2e84430654dba83ce3fa7abf398b28: #587 
- 577bffecd0cd47d39ab9d50d3805a38de962eefa: #593 
- e5cabfa0a86bdb8ca461eada27b06dc4a3c87028: #603 
- 2d371a049d743493aa21a9b7181d59a8680445e5: #609 
- 6dfbe524485ed03490894e5c0f31bc7fc2349ff5: #611 
- 86176e8c5e8c63f418ed2f71bead3abe0b5f2ccb: #615
=> chore: patch on branch `release-2.3`

content/oci/storage.go, content/oci/storage_test.go
=> fix: error handling when delete non-existent target

registry/reference.go
Include values of the artifact and or related context in the errors - 
This is related to https://github.com/oras-project/oras/pull/1152. See the oras-project/oras#1152 to see the updates to output of errors.
=> chore: add reference details to errors

copy.go, copy_test.go
Export `ErrSkipDesc` as `ErrSkipDesc` allows users of the library to implement `CopyGraphOptions.PreCopy` to call `Mount()` and then return `ErrSkipDesc` from `PreCopy` which bypasses the downstream copy operation.
Closes #580
=> feat: minimal change to support cross-repo blob mounting

copy.go, copy_test.go
=> fix: rename ErrSkipDesc to SkipNode

example_copy_test.go, extendedcopy_test.go, registry/remote/example_test.go, registry/remote/repository.go, registry/remote/repository_test.go
When accessing the referrer's API, this adds a check to make sure the content-type is an OCI index.
Also fixes the tests to properly set the content-type header in the response.
Closes #633
=> fix: check content-type when using referrers API

content/oci/oci.go, content/oci/oci_test.go, content/resolver.go
Hi!
`oci.Store` offers the possibility to tag images but not to untag them.
This is a problem when you want to remove images because you only want to untag a tag when several point to the same image (_e.g._ `docker rmi` and see https://github.com/inspektor-gadget/inspektor-gadget/pull/2162#pullrequestreview-1740423646).
I will add proper testing if we agree that this addition is useful to the package.
Best regards and thank you in advance.
=> feat: add `Untag()` to `*oci.Store`

registry/remote/auth/cache.go, registry/remote/auth/cache_test.go
This PR adds a new exported method called `NewRobustCache()` and changes the `DefaultCache` to use the robust cache.  The robust cache uses scoped based auth but falls back to host based auth to better handle the situations described in #650 but retain the benefits of scoped based auth (where the token for a repo might be different than another repo in the same registry).
Closes #650
=> feat: add a host-based auth cache as a fallback

copy.go, copy_test.go, example_copy_test.go, registry/remote/repository_test.go
Adds MountFrom and OnMounted to CopyGraphOptions.
Allows for trying to mount from multiple repositories.
Closes #580 
I think this is a better approach than my other PR #632
=> feat: add MountFrom and OnMounted to CopyGraphOptions

content/oci/oci.go, content/oci/oci_test.go, content/oci/storage.go, internal/graph/memory.go, internal/graph/memory_test.go
=> feat: Public GC function of `oci.Store`

pkg/auth/docker/login.go, pkg/auth/docker/login_tls.go
`types.AuthConfig` removed in github.com/docker/docker@v25, can't update to it
=> fix: get rid of deprecated types.AuthConfig

go.mod, go.sum
=> build(deps): use image-spec v1.1.0-rc6 instead of rc.6

content/file/file.go, content/file/file_test.go
=> feat: allow skip unpack on push to file store

content/oci/oci.go, registry/reference.go, registry/remote/errcode/errors.go, registry/remote/example_test.go, registry/remote/referrers.go, registry/remote/registry.go, registry/remote/repository.go, registry/remote/repository_test.go, registry/remote/url.go, registry/remote/warning.go, registry/repository.go
1. If the `OCI-Subject` header is not set in the response of manifest push, do not ping the Referrers API (see `repository.go`)
2. Update tests accordingly
3. Update the spec version in comments
Resolve: #685
=> refactor: upgrade to `distribution-spec v1.1.0-rc4`

internal/platform/platform.go, internal/platform/platform_test.go
=> fix: fix the potential panic error if there is no platform in the index or manifest list

content/oci/oci.go, content/oci/readonlyoci.go, content/oci/readonlystorage.go, content/oci/storage.go, example_pack_test.go, example_test.go, pack.go, pack_test.go, registry/reference.go, registry/remote/errcode/errors.go, registry/remote/referrers.go, registry/remote/registry.go, registry/remote/repository.go, registry/remote/url.go, registry/remote/warning.go, registry/repository.go
=> feat: upgrade to distribution-spec v1.1.0

internal/ioutil/io.go, internal/ioutil/io_test.go
Add a new unit test case by the change to `UnwrapNopCloser` introduced by #715
=> test: add a new case for UnwrapNopCloser

registry/reference.go, registry/reference_test.go
=> fix: check empty registry name

content/file/file.go, content/file/file_test.go
=> fix(file.Store): fix race condition on restoring the same named content

MIGRATION_GUIDE.md, copy.go, extendedcopy.go
1. Update MIGRATION_GUIDE.md
2. Revise the go doc comments for Copy and Extended Copy to make it easier to understand
Resolve: #735
=> docs: update migration guide and copy doc

content/file/file_test.go
Fix file closing issue `The process cannot access the file because it is being used by another process.` on Windows for the test `TestStore_Dir_Push_SkipUnpack`.
=> test: fix file closing issue on windows

example_pack_test.go, pack.go
=> docs: document PackManifestOptions to make PackManifest reproducible

internal/fs/tarfs/tarfs.go
When opening a folder as OCI image layout and there is no `oci-layout` file exists, the error would be
> failed to open OCI layout file:  oci-layout: file does not exist
There is a duplicated space in the error string, because the `Op` field is missing in the returned `fs.PathError`. With fix in this PR, the return error would be
> failed to open OCI layout file: open oci-layout: file does not exist
Fixes #640
=> fix: add missing operation to fs path error

content/file/file.go, content/file/utils.go, content/file/utils_test.go
=> feat: support context cancellation in file store

content/oci/storage.go
=> fix: check close error in `oci/storage.go` during ingestion

.github/.codecov.yml, content/graph_test.go, content/limitedstorage_test.go, content/storage_test.go, copy_test.go, extendedcopy_test.go, internal/fs/tarfs/tarfs_test.go, internal/manifestutil/parser_test.go, registry/reference_test.go, registry/remote/credentials/trace/trace_test.go, registry/remote/registry_test.go, registry/remote/repository.go, registry/remote/repository_test.go, registry/remote/utils_test.go
1. Increase unit test coverage to 80%
2. Set Codecov threshold to 80%
Resolves: #779
=> test: increase unit test coverage to 80%

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml, README.md, go.mod
1. Upgrading `go.mod` to `1.23`
2. Update go version window to `[1.23, 1.24]` for GitHub builds
Resolves: #890
=> build(go): shift Go support window to [1.23, 1.24]

content/oci/oci.go, content/oci/oci_test.go
Add a media type field in the `index.json` file generated during the OCI store initialization.
Fixes: #880
=> fix: add media type in the generated index.json file

registry/remote/repository.go, registry/remote/repository_test.go
1. Verify the `Docker-Content-Digest header` against the descriptor digest in `Repository.Blobs().Fetch()`
2. Add corresponding unit tests
Fixes: #895
=> fix: check the `Docker-Content-Digest` header in `Repository.Blobs().Fetch()`

content/file/errors.go, content/file/file.go, content/file/utils.go, content/file/utils_test.go, content/file/utils_unix_test.go
This PR takes care of https://github.com/oras-project/oras-go/issues/886, or rather part of it.
It adds an option to the File store that's similar to tar's `--preserve-permissions`.
closes https://github.com/oras-project/oras-go/issues/886
=> feat: option to have File store preserve permissions when extracting

content/oci/oci.go, content/oci/readonlyoci.go, content/oci/readonlystorage.go, content/oci/storage.go, example_pack_test.go, internal/spec/artifact.go, pack.go, registry/reference.go, registry/remote/errcode/errors.go, registry/remote/referrers.go, registry/remote/registry.go, registry/remote/repository.go, registry/remote/url.go, registry/remote/warning.go, registry/repository.go
1. Use the media type regex defined in [`image-spec v1.1.1`](https://github.com/opencontainers/image-spec/blob/v1.1.1/schema/defs-descriptor.json#L7) in `pack.go`
2. Update the doc links to reference `image-spec v1.1.1` and `distribution-spec v1.1.1`
Resolves: #910
=> chore: update to `image-spec v1.1.1`

go.mod, go.sum
=> build(deps): bump golang.org/x/sync from 0.11.0 to 0.12.0

internal/syncutil/limit.go, internal/syncutil/limit_test.go, internal/syncutil/limitgroup.go, internal/syncutil/limitgroup_test.go
1. Remove the use of `atomic.Value`
2. Cancel all go-routines before releasing semaphore permits
3. Wait for schedule go-routines to release the semaphore permits before returning
4. Add unit tests
Fixes #916, fixes #908
=> fix: fix concurrency bugs causing panics and race conditions in `internal/syncutil`

content/example_test.go, content/file/example_test.go, example_copy_test.go, registry/remote/example_test.go
(hopefully) fixes #818 
This PR:
1. Update the outdated examples involving `Pack` and `ArtifactManifest`.
2. Add numbered step documentation to the two package level examples of copy, so that there is a consistency with the other four package level examples.
3. Minor fixes such as renaming examples.
=> docs: update example tests

README.md, docs/README.md, docs/Targets.md
1. Add a `README.md` file for the `docs` directory
2. Refine the `README.md` file for the project
- Add a brief introduction for the repo
- Add more documentation links
- Reorganize
3. Add explanation about tag update in `docs/Targets.md`
Resolve: #813
=> docs: improve README.md

registry/remote/credentials/registry.go, registry/remote/credentials/registry_test.go
Login and logout should be supported for the OCI registry server `registry-1.docker.io` as well as the alias `docker.io` The key used is the legacy server for backward compatibility.
Related: https://github.com/helm/helm/issues/30929
=> fix: credentials key for docker registry-1
